In [ ]:
import torch

In [ ]:
in2hid = torch.nn.Linear(2,2)
hit2out = torch.nn.Linear(2,1)

In [ ]:
import torch.utils.data

input = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
target = torch.Tensor([[0], [1], [1], [0]])
xdata = torch.utils.data.TensorDataset(input, target)
torchLoader = torch.utils.data.DataLoader(xdata, batch_size=4)
print(xdata, torchLoader)

In [ ]:
import torch
import torch.utils.data
import numpy as np

lr = 1.9 # learning rate
mom = 0.0 # momentum

class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.A = torch.nn.Parameter(torch.zeros((1), requires_grad=True))
    def forward(self, input):
        output  = self.A * input
        return(output)

device = 'cpu'

input  = torch.Tensor([[1]])
target = torch.Tensor([[1]])

slope_dataset = torch.utils.data.TensorDataset(input,target)
train_loader  = torch.utils.data.DataLoader(slope_dataset,batch_size=1)

# create neural network according to model specification
net = MyModel().to(device) # CPU or GPU

# choose between SGD, Adam or other optimizer
optimizer = torch.optim.SGD(net.parameters(),lr=lr,momentum=mom)

epochs = 1000

for epoch in range(1, epochs):
    for batch_id, (data,target) in enumerate(train_loader):
        optimizer.zero_grad() # zero the gradients
        output = net(data)    # apply network
        loss = 0.5*torch.mean((output-target)*(output-target))
        if type(net.A.grad) == type(None):
            print('Ep%3d: zero_grad(): A.grad=  None  A.data=%7.4f loss=%7.4f' \
                      % (epoch, net.A.data, loss))
        else:
            print('Ep%3d: zero_grad(): A.grad=%7.4f A.data=%7.4f loss=%7.4f' \
                      % (epoch, net.A.grad, net.A.data, loss))
        loss.backward()       # compute gradients
        optimizer.step()      # update weights
        print('            step(): A.grad=%7.4f A.data=%7.4f' \
                      % (net.A.grad, net.A.data))
        if loss < 0.000000001 or np.isnan(loss.data):
            exit(0)

In [2]:
"""
TODO: Implement a simple tensor addition x + y. 
Assign the result to z. 
"""
import torch

shape = (2,3,)
x = torch.rand(shape)
y = torch.rand(shape)
z = torch.zeros(shape)

z = torch.add(x, y)

print("x = :")
print(x)
print("y = :")
print(y)

print("\n")

print("x + y = :")
print(z)
print("\n")

x = :
tensor([[0.8105, 0.6674, 0.8232],
        [0.4895, 0.5515, 0.7536]])
y = :
tensor([[0.2710, 0.2915, 0.5700],
        [0.5313, 0.5813, 0.8741]])


x + y = :
tensor([[1.0815, 0.9589, 1.3932],
        [1.0208, 1.1329, 1.6276]])




In [5]:
z = torch.rand([2,3])
new_shape = (3,2)

"""
TODO: Reshapes the tensor z with the given shape (new_shape) 
Hint: use view()
"""
print(z)
z = z.view(new_shape)

print("z and its shape after reshaping:")
print(z)
print(z.shape)
print("\n")

tensor([[0.5116, 0.1707, 0.9792],
        [0.6787, 0.6318, 0.0345]])
z and its shape after reshaping:
tensor([[0.5116, 0.1707],
        [0.9792, 0.6787],
        [0.6318, 0.0345]])
torch.Size([3, 2])




# Flatten

In [8]:
z = torch.rand([2,3])
"""
Flatten
TODO: Flatten the tensor z.
Hint: use view()
"""

z = z.view([z.shape[0]*z.shape[1]])

# you can also use z = torch.flatten(z) in case z is not contiguous.

print("z and its shape after the flatten operation:")
print(z)
print(z.shape)
print("\n")

z and its shape after the flatten operation:
tensor([0.5071, 0.0168, 0.7940, 0.0651, 0.3566, 0.7034])
torch.Size([6])




# Transpose

In [10]:
z = torch.rand([2,3])

"""
TODO: Swaps the first dimension and the second dimension of z.
"""
print(z)
z = torch.transpose(z, 0, 1)


print("z and its shape after the transpose operation:")
print(z)
print(z.shape)
print("\n")

tensor([[0.8558, 0.6278, 0.0282],
        [0.1189, 0.8003, 0.0479]])
z and its shape after the transpose operation:
tensor([[0.8558, 0.1189],
        [0.6278, 0.8003],
        [0.0282, 0.0479]])
torch.Size([3, 2])




# Permutation

In [11]:
"""
Permutation
TODO: Permute the dimensions of z according to the given order (swapping axes). here is (3,5,1) ->
(1,3,5)
"""

# Create a new tensor
shape = (3,5,1)
z = torch.rand(shape)
order = [2,0,1]
print(z)

z = torch.permute(z, order)

print("z and its shape after permutation")
print(z)
print(z.shape)
print("\n")

tensor([[[0.4273],
         [0.8112],
         [0.7757],
         [0.4968],
         [0.2542]],

        [[0.3912],
         [0.0010],
         [0.2597],
         [0.3385],
         [0.1966]],

        [[0.6381],
         [0.2678],
         [0.3850],
         [0.2426],
         [0.3182]]])
z and its shape after permutation
tensor([[[0.4273, 0.8112, 0.7757, 0.4968, 0.2542],
         [0.3912, 0.0010, 0.2597, 0.3385, 0.1966],
         [0.6381, 0.2678, 0.3850, 0.2426, 0.3182]]])
torch.Size([1, 3, 5])




# Dot Product

In [12]:
"""
TODO: Calculate the dot product of
      two rank 1 tensors (vectors) u and v.
"""


# Create two vectors
v = torch.tensor([2, 3])
u = torch.tensor([2, 1])

result = torch.dot(v, u)

print("The dot product of u and v:")
print(result.item())
print("\n")

The dot product of u and v:
7




# Concatenation

In [14]:
shape = (2,3,)
x = torch.rand(shape)
y = torch.rand(shape)

"""
TODO: Concatenate (x,y) in dimension 1.
"""
z = torch.concat((x, y), 1)

print("The Concatenated tensor z of (x, y)")
print(z)
print("\n")

The Concatenated tensor z of (x, y)
tensor([[0.7539, 0.8544, 0.6248, 0.3019, 0.7224, 0.6188],
        [0.0924, 0.3479, 0.8331, 0.0982, 0.3576, 0.6090]])


